  spf.task:
  environment: production # Indicates this is the production environment
  admin-email: admin@prod.com # Admin contact (use env variable in real prod)
  default-priority: HIGH  # Default priority for new tasks
  notifications-enabled: true   # Disabled notifications (verify if intentional)
  max-title-length: 200 # Maximum allowed length for task titles
  # Sample tasks for demonstration;
  sample-data-enabled: false  # Add this flag to guard loading sample tasks
  sample-tasks:
    - title: "Prod Task 1"
      assignee-email: "prod1@test.com"
      description: "First Prod task"
      status: "TODO"
      priority: "MEDIUM"
      createdAt: "2025-08-01T10:00:00"
    - title: "Prod Task 2"
      assignee-email: "prod2@test.com"
      description: "Second Prod task"
      status: "IN_PROGRESS"
      priority: "high"
      createdAt: "2025-09-11T10:00:00"
  app:
    - isNotificationsEnabled: true